const CART_ADD_REQUEST = "CART_ADD_REQUEST";
const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
const CART_REMOVE = "CART_REMOV";
const CART_UPDATE_AMOUNT_REQUEST = "CART_UPDATE_AMOUNT_REQUEST";  
const CART_UPDATE_AMOUNT_SUCCESS = "CART_UPDATE_AMOUNT_SUCCESS";

export {
  CART_ADD_REQUEST,
  CART_ADD_SUCCESS,
  CART_REMOVE,
  CART_UPDATE_AMOUNT_REQUEST,
  CART_UPDATE_AMOUNT_SUCCESS,
};
