const USER_FETCH_LOADING = 'USER_FETCH_LOADING';
const USER_FETCH_SUCCEED = 'USER_FETCH_SUCCEED';
const USER_FETCH_ERROR = 'USER_FETCH_ERROR';
const USER_FETCH_RESET = 'USER_FETCH_RESET';

export {
  USER_FETCH_LOADING,
  USER_FETCH_SUCCEED,
  USER_FETCH_ERROR,
  USER_FETCH_RESET,
};